# JEKYLL CONFIGURATION
#
# This is the main conifuration for this Guides Jekyll setup.
# For more information see https://jekyllrb.com/docs/configuration/#configuration-settings


# TEAM SETTINGS
team: Content Guide Team
email_team: content@digital.gov.au

# GUIDE SETTINGS
title: Content Guide
url: https://guides.service.gov.au/content-guide/
description: A guide to help Australian Government teams design simple, clear and fast content.
github_url: https://github.com/govau/content-guide
google_analytics: UA-61222473-19

# LICENSE SETTINGS
#
# We're presuming you use GitHub, and have the license file in master, titled `LICENSE.md`
license: CC BY 4.0


# UI Kit URL for javascript includes
#
# This needs to be abstracted eventually into a styles gem?
uikit_github_url: https://github.com/AusDTO/gov-au-ui-kit
uikit_base_url: https://gov-au-ui-kit.apps.staging.digital.gov.au/


# MARKDOWN FLAVOUR
#
# There are numerous ‘flavours’ (super sets) of Markdown.
# We opt for kramdown: https://kramdown.gettalong.org/
#
# This is b/c kramdown has support for the Markdown super set goodies like
# definition lists, abbreviations, and footnotes.
#
# Syntax reference: https://kramdown.gettalong.org/syntax.html
markdown: kramdown

# BUILD INCLUDES
#
# Directories that start with a "_" or "." are ignored, except for those included here.
include: ["_pages"]

# BUILD EXCLUDES
#
# These files are ignored when Jekyll builds the site.
exclude: [
  "node_modules",
  "_data",
  "vendor",
  "bin",
  ".DS_Store",
  "Gemfile",
  "Gemfile.lock",
  "Rakefile",
  "circle.yml",
  "_config*.yml",
  "config.ru",
  "ld_library_path",
  "LICENSE.md",
  "manifest*.yml",
  "yarn.lock",
  "README.md",
  "*.sublime-project",
  "Dockerfile",
  ".asset-cache"
]


# PLUGINS
#
# These are additional Ruby gems this guide relies on.
plugins:
  - jekyll-assets # https://github.com/jekyll/jekyll-assets
  - rouge # https://github.com/jneen/rouge


# ASSET PIPELINE SETTINGS
#
# We use jekyll-assets: https://github.com/jekyll/jekyll-assets
assets:
  assets:
    - "*.png"
    - "*.gif"
    - "*.svg"
  sources:
    - _assets/scss
    - _assets/img
    - _assets/js
    - _assets/js/vendor
    - _assets/vendor/ds


# HIGHLIGHTER
#
# Code syntax highlighting
highlighter: rouge


# COLLECTIONS CONFIGURATION
#
# @required
#   title         {string}   The name of the collection for display in navigation
#   description   {string}   Text for category description
#   order         {integer}  The order attribute is used to sort the navigation.
#   output        {boolean}  Whether or not to render the pages out
#
# For example:
# collections:
#   dummy-collection:
#     title: "Dummy collection title"
#     description: "The description for this collection. It is placed on the homepage listing."
#     order: 0
#     output: false
#
collections:
  content-structure:
    title: "Content structure"
    description: "The basic building blocks for crafting good content."
    order: 1
  writing-style:
    title: "Writing style"
    description: "Guidance on writing plain English content that reflects a modern government voice."
    order: 2
  accessibility-inclusivity:
    title: "Accessibility and inclusivity"
    description: "How to design content for First Australians, people who speak languages other than English and people with disability."
    order: 3
  punctuation-grammar:
    title: "Punctuation and grammar"
    description: "How to punctuate and capitalise content for screens."
    order: 4
  terms-phrases:
    title: "Terms and phrases"
    description: "Spellings of commonly used government and digital words and terms."
    order: 5
  numbers-measurements:
    title: "Numbers and measurements"
    description: "Guidance for writing numbers on screens."
    order: 6
  formatting:
    title: "Formatting"
    description: "How to use italic, bold and underline."
    order: 7
  types-of-content:
    title: "Types of content"
    description: "How to create and use common kinds of content."
    order: 8
  search-engines:
    title: "Writing for search engines"
    description: "How to write content that will help search engines find and rank your information."
    order: 9

# PROSE.IO
#
# Configuration for the htt://prose.io editor.
prose:
#  rooturl: ''
  siteurl: 'http://gov.au/alpha'
  ignore:
    - _config.yml
    - /manifest.yml
    - /circle.yml
    - /_assets
    - /_data
    - /_layouts
    - /_includes
    - /_plugins
    - /_posts
    - /assets
    - /bin
    - /fonts
    - /css
    - /js
    - /Staticfile
    - /Staticfile.auth
    - /Gemfile
    - /Gemfile.lock
    - /.ruby-version
    - /.gitignore
    - /feed.xml
